name: NodeJS with Webpack

on:
  push:
    branches: ['fix']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: meatball0225/guildweb_db:v1.1
        env:
          MYSQL_ROOT_PASSWORD: '123456'
          MYSQL_DATABASE: 'GuildWeb'
          MYSQL_USER: 'yun'
          MYSQL_PASSWORD: '123456'
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h"127.0.0.1" --silent; then
              break
            fi
            echo 'Waiting for MySQL to be ready...'
            sleep 1
          done
          if [ "$i" = 0 ]; then
            echo 'MySQL did not become ready in time'
            exit 1
          fi

      - name: Install dependencies
        run: cd ./backend && npm install

      - name: tsc --watch
        run: cd ./backend && npm run check

      - name: Start application
        run: |
          export NODE_ENV=development
          export DB_HOST=localhost
          export DB_USER=yun
          export DB_PASSWORD=123456
          export DB_NAME=GuildWeb
          export BE_PORT=3010
          cd ./backend && npm start
